server:
  port: 8082

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus?currentSchema=payments
    username: nexus
    password: nexus
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: payments
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    schemas: payments
    default-schema: payments
  kafka:
    bootstrap-servers: localhost:9092

payment:
  success-rate: 0.8

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: payment-service

logging:
  pattern:
    console: '{"timestamp":"%d{ISO8601}","level":"%p","service":"payment-service","traceId":"%X{traceId:-}","spanId":"%X{spanId:-}","message":"%m"}%n'
